# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0002_liveblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblog',
            name='post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='liveblog_liveblog', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
