# Generated by Django 4.2.21 on 2025-06-03 09:20

import cms.models.fields
import django.db.models.deletion
import djangocms_text.fields
import djangocms_text_ckeditor.fields
import filer.fields.image
import meta.models
import parler.fields
import sortedm2m.fields
import taggit_autosuggest.managers
from django.conf import settings
from django.db import migrations, models
from django.db.models import ForeignKey


class Migration(migrations.Migration):
    replaces = [
        ("djangocms_blog", "0001_initial"),
        ("djangocms_blog", "0002_post_sites"),
        ("djangocms_blog", "0003_auto_20141201_2252"),
        ("djangocms_blog", "0004_auto_20150108_1435"),
        ("djangocms_blog", "0005_auto_20150212_1118"),
        ("djangocms_blog", "0006_auto_20150214_1907"),
        ("djangocms_blog", "0007_auto_20150719_0933"),
        ("djangocms_blog", "0008_auto_20150814_0831"),
        ("djangocms_blog", "0009_latestpostsplugin_tags_new"),
        ("djangocms_blog", "0010_auto_20150923_1151"),
        ("djangocms_blog", "0011_auto_20151024_1809"),
        ("djangocms_blog", "0012_auto_20151220_1734"),
        ("djangocms_blog", "0013_auto_20160201_2235"),
        ("djangocms_blog", "0014_auto_20160215_1331"),
        ("djangocms_blog", "0015_auto_20160408_1849"),
        ("djangocms_blog", "0016_auto_20160502_1741"),
        ("djangocms_blog", "0017_thumbnail_move"),
        ("djangocms_blog", "0018_thumbnail_move2"),
        ("djangocms_blog", "0019_thumbnail_move3"),
        ("djangocms_blog", "0020_thumbnail_move4"),
        ("djangocms_blog", "0021_post_liveblog"),
        ("djangocms_blog", "0022_auto_20160605_2305"),
        ("djangocms_blog", "0023_auto_20160626_1539"),
        ("djangocms_blog", "0024_auto_20160706_1524"),
        ("djangocms_blog", "0025_auto_20160803_0858"),
        ("djangocms_blog", "0021_auto_20160823_2008"),
        ("djangocms_blog", "0026_merge"),
        ("djangocms_blog", "0027_post_date_featured"),
        ("djangocms_blog", "0028_auto_20170304_1040"),
        ("djangocms_blog", "0029_post_related"),
        ("djangocms_blog", "0030_auto_20170509_1831"),
        ("djangocms_blog", "0031_auto_20170610_1744"),
        ("djangocms_blog", "0032_auto_20180109_0023"),
        ("djangocms_blog", "0033_auto_20180226_1410"),
        ("djangocms_blog", "0022_auto_20170304_1040"),
        ("djangocms_blog", "0034_merge"),
        ("djangocms_blog", "0035_posttranslation_subtitle"),
        ("djangocms_blog", "0036_auto_20180913_1809"),
        ("djangocms_blog", "0037_auto_20190806_0743"),
        ("djangocms_blog", "0038_post_media"),
        ("djangocms_blog", "0039_auto_20200331_2227"),
    ]

    initial = True

    dependencies = [
        ("filer", "0003_thumbnailoption"),
        ("filer", "__first__"),
        ("cms", "0004_auto_20140924_1038"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "__first__"),
        ("taggit", "__first__"),
        ("cms", "0020_old_tree_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=100, verbose_name="Type")),
                (
                    "namespace",
                    models.CharField(default=None, max_length=100, unique=True, verbose_name="Instance namespace"),
                ),
                ("app_data", django.db.models.TextField(default="{}", editable=False)),
            ],
            options={
                "abstract": False,
                "verbose_name": "blog config",
                "verbose_name_plural": "blog configs",
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("date_modified", models.DateTimeField(auto_now=True, verbose_name="modified at")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="djangocms_blog.blogcategory",
                        verbose_name="parent",
                    ),
                ),
                (
                    "app_config",
                    models.ForeignKey(
                        help_text="When selecting a value, the form is reloaded to get the updated default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_blog.blogconfig",
                        verbose_name="app. config",
                    ),
                ),
            ],
            options={
                "verbose_name": "blog category",
                "verbose_name_plural": "blog categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("date_modified", models.DateTimeField(auto_now=True, verbose_name="last modified")),
                ("date_published", models.DateTimeField(blank=True, null=True, verbose_name="published since")),
                ("date_published_end", models.DateTimeField(blank=True, null=True, verbose_name="published until")),
                ("publish", models.BooleanField(default=False, verbose_name="publish")),
                ("enable_comments", models.BooleanField(default=True, verbose_name="enable comments on post")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="djangocms_blog_post_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_posts",
                        to="djangocms_blog.blogcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "content",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_content",
                        slotname="post_content",
                        to="cms.placeholder",
                    ),
                ),
                (
                    "main_image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="djangocms_blog_post_image",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="main image",
                    ),
                ),
                (
                    "tags",
                    taggit_autosuggest.managers.TaggableManager(
                        blank=True,
                        help_text="Type a tag and hit tab, or start typing and select from autocomplete list.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select sites in which to show the post. If none is set it will be visible in all the configured sites.",
                        to="sites.site",
                        verbose_name="Site(s)",
                    ),
                ),
                (
                    "app_config",
                    models.ForeignKey(
                        help_text="When selecting a value, the form is reloaded to get the updated default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_blog.blogconfig",
                        verbose_name="app. config",
                    ),
                ),
                (
                    "main_image_full",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="djangocms_blog_post_full",
                        to="filer.thumbnailoption",
                        verbose_name="main image full",
                    ),
                ),
                (
                    "main_image_thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="djangocms_blog_post_thumbnail",
                        to="filer.thumbnailoption",
                        verbose_name="main image thumbnail",
                    ),
                ),
                (
                    "liveblog",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_blog",
                        slotname="live_blog",
                        to="cms.placeholder",
                    ),
                ),
                ("enable_liveblog", models.BooleanField(default=False, verbose_name="enable liveblog on post")),
                ("date_featured", models.DateTimeField(blank=True, null=True, verbose_name="featured date")),
                (
                    "related",
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, to="djangocms_blog.post", verbose_name="Related Posts"
                    ),
                ),
                (
                    "media",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        slotname="media",
                        to="cms.placeholder",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_published", "-date_created"),
                "get_latest_by": "date_published",
                "verbose_name": "blog article",
                "verbose_name_plural": "blog articles",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="GenericBlogPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="djangocms_blog_genericblogplugin",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "app_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="When selecting a value, the form is reloaded to get the updated default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_blog.blogconfig",
                        verbose_name="app. config",
                    ),
                ),
                (
                    "current_site",
                    models.BooleanField(
                        default=True, help_text="Select items from the current site only", verbose_name="current site"
                    ),
                ),
                (
                    "template_folder",
                    models.CharField(
                        choices=[("plugins", "Default template")],
                        default="plugins",
                        help_text="Select plugin template to load for this instance",
                        max_length=200,
                        verbose_name="Plugin template",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="AuthorEntriesPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="djangocms_blog_authorentriesplugin",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "latest_posts",
                    models.IntegerField(
                        default=5, help_text="The number of author articles to be displayed.", verbose_name="articles"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        limit_choices_to={"djangocms_blog_post_author__publish": True},
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="authors",
                    ),
                ),
                (
                    "app_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="When selecting a value, the form is reloaded to get the updated default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_blog.blogconfig",
                        verbose_name="app. config",
                    ),
                ),
                (
                    "current_site",
                    models.BooleanField(
                        default=True, help_text="Select items from the current site only", verbose_name="current site"
                    ),
                ),
                (
                    "template_folder",
                    models.CharField(
                        choices=[("plugins", "Default template")],
                        default="plugins",
                        help_text="Select plugin template to load for this instance",
                        max_length=200,
                        verbose_name="Plugin template",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BlogConfigTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("app_title", models.CharField(max_length=234, verbose_name="application title")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="djangocms_blog.blogconfig",
                    ),
                ),
                ("object_name", models.CharField(default="Article", max_length=234, verbose_name="object name")),
            ],
            options={
                "verbose_name": "blog config Translation",
                "db_table": "djangocms_blog_blogconfig_translation",
                "default_permissions": (),
                "db_tablespace": "",
                "managed": True,
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.CreateModel(
            name="LatestPostsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="djangocms_blog_latestpostsplugin",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "latest_posts",
                    models.IntegerField(
                        default=5, help_text="The number of latests articles to be displayed.", verbose_name="articles"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Show only the blog articles tagged with chosen categories.",
                        to="djangocms_blog.blogcategory",
                        verbose_name="filter by category",
                    ),
                ),
                (
                    "tags",
                    taggit_autosuggest.managers.TaggableManager(
                        blank=True,
                        help_text="Show only the blog articles tagged with chosen tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="filter by tag",
                    ),
                ),
                (
                    "app_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="When selecting a value, the form is reloaded to get the updated default",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_blog.blogconfig",
                        verbose_name="app. config",
                    ),
                ),
                (
                    "current_site",
                    models.BooleanField(
                        default=True, help_text="Select items from the current site only", verbose_name="current site"
                    ),
                ),
                (
                    "template_folder",
                    models.CharField(
                        choices=[("plugins", "Default template")],
                        default="plugins",
                        help_text="Select plugin template to load for this instance",
                        max_length=200,
                        verbose_name="Plugin template",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BlogCategoryTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("name", models.CharField(max_length=752, verbose_name="name")),
                ("slug", models.SlugField(blank=True, max_length=752, verbose_name="slug")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="djangocms_blog.blogcategory",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, default="", verbose_name="category meta description"),
                ),
            ],
            options={
                "db_table": "djangocms_blog_blogcategory_translation",
                "verbose_name": "blog category Translation",
                "default_permissions": (),
                "unique_together": {("language_code", "master"), ("language_code", "slug")},
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(max_length=752, verbose_name="title")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=752, verbose_name="slug")),
                (
                    "abstract",
                    djangocms_text_ckeditor.fields.HTMLField(blank=True, default="", verbose_name="abstract"),
                ),
                ("meta_description", models.TextField(blank=True, default="", verbose_name="post meta description")),
                ("meta_keywords", models.TextField(blank=True, default="", verbose_name="post meta keywords")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="used in title tag and social sharing",
                        max_length=2000,
                        verbose_name="post meta title",
                    ),
                ),
                ("post_text", djangocms_text.fields.HTMLField(blank=True, default="", verbose_name="text")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="djangocms_blog.post",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, default="", max_length=767, verbose_name="subtitle")),
            ],
            options={
                "db_table": "djangocms_blog_post_translation",
                "verbose_name": "blog article Translation",
                "default_permissions": (),
                "unique_together": {("language_code", "master"), ("language_code", "slug")},
                "managed": True,
            },
        ),
    ]
