# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0021_post_liveblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enable_liveblog',
            field=models.BooleanField(default=False, verbose_name='enable liveblog on post'),
        ),
    ]
