# Generated by Django 1.9.12 on 2017-03-04 09:40

from distutils.version import LooseVersion

import aldryn_apphooks_config
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0021_auto_20160823_2008"),
    ]

    if LooseVersion(aldryn_apphooks_config.__version__) > LooseVersion("0.3.0"):
        operations = [
            migrations.AlterField(
                model_name="blogconfig",
                name="namespace",
                field=models.CharField(default=None, max_length=100, unique=True, verbose_name="Instance namespace"),
            ),
            migrations.AlterField(
                model_name="blogconfig",
                name="type",
                field=models.CharField(max_length=100, verbose_name="Type"),
            ),
        ]
