# Generated by Django 1.9.6 on 2016-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0022_auto_20160605_2305"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorentriesplugin",
            name="current_site",
            field=models.BooleanField(
                default=True, help_text="Select items from the current site only", verbose_name="current site"
            ),
        ),
        migrations.AddField(
            model_name="genericblogplugin",
            name="current_site",
            field=models.BooleanField(
                default=True, help_text="Select items from the current site only", verbose_name="current site"
            ),
        ),
        migrations.AddField(
            model_name="latestpostsplugin",
            name="current_site",
            field=models.BooleanField(
                default=True, help_text="Select items from the current site only", verbose_name="current site"
            ),
        ),
    ]
