# Generated by Django 1.9.9 on 2016-08-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0021_auto_20160823_2008"),
        ("djangocms_blog", "0025_auto_20160803_0858"),
    ]

    operations = []
