# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0026_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorentriesplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template')], default='plugins', help_text='Select plugin template to load for this instance', max_length=200, verbose_name='Plugin template'),
        ),
        migrations.AlterField(
            model_name='genericblogplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template')], default='plugins', help_text='Select plugin template to load for this instance', max_length=200, verbose_name='Plugin template'),
        ),
        migrations.AlterField(
            model_name='latestpostsplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template')], default='plugins', help_text='Select plugin template to load for this instance', max_length=200, verbose_name='Plugin template'),
        ),
    ]
