# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0027_post_date_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogconfig',
            name='namespace',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AlterField(
            model_name='blogconfig',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
    ]
