# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 05:28
from __future__ import unicode_literals

from django.db import migrations
import djangocms_blog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0029_post_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=djangocms_blog.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, max_length=255, verbose_name='slug'),
        ),
    ]
