# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0029_post_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date_published', 'ordering': ('post_order', '-date_published', '-date_created'), 'verbose_name': 'blog article', 'verbose_name_plural': 'blog articles'},
        ),
        migrations.AddField(
            model_name='post',
            name='post_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
