# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0029_blogcategory_main_image'),
        ('djangocms_blog', '0031_auto_20170610_1744'),
    ]

    operations = [
    ]
