# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0032_merge_20170727_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorytranslation',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='post meta description'),
        ),
        migrations.AddField(
            model_name='blogcategorytranslation',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='post meta keywords'),
        ),
        migrations.AddField(
            model_name='blogcategorytranslation',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='used in title tag and social sharing', max_length=255, verbose_name='post meta title'),
        ),
    ]
