# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0033_auto_20170809_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='Hits'),
        ),
    ]
