# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0034_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='import_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Blog category import id'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order_by',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
