# Generated by Django 1.11 on 2018-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0034_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttranslation",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=767, verbose_name="subtitle"),
        ),
    ]
