# Generated by Django 1.11.15 on 2018-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0035_posttranslation_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttranslation",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=752, verbose_name="slug"),
        ),
    ]
