# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0035_auto_20170911_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_category_image', verbose_name='Blog category image'),
        ),
    ]
