# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0035_posttranslation_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked_content_url',
            field=models.URLField(blank=True, help_text='Enter URL of linked content, like an external image, video or audio', null=True, verbose_name='linked content url'),
        ),
    ]
