# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 18:09
from __future__ import unicode_literals

from django.db import migrations
import djangocms_blog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0035_posttranslation_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=djangocms_blog.fields.AutoSlugField(allow_unicode=True, blank=True, max_length=767, verbose_name='slug'),
        ),
    ]
