# Generated by Django 2.1.11 on 2019-08-06 05:43

import django.db.models.deletion
import parler.fields
import taggit_autosuggest.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0036_auto_20180913_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorentriesplugin",
            name="authors",
            field=models.ManyToManyField(
                limit_choices_to={"djangocms_blog_post_author__publish": True},
                to=settings.AUTH_USER_MODEL,
                verbose_name="authors",
            ),
        ),
        migrations.AlterField(
            model_name="blogcategorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="djangocms_blog.BlogCategory",
            ),
        ),
        migrations.AlterField(
            model_name="blogconfigtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="djangocms_blog.BlogConfig",
            ),
        ),
        migrations.AlterField(
            model_name="latestpostsplugin",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="Show only the blog articles tagged with chosen tags.",
                related_name="djangocms_blog_latest_post",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="filter by tag",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="Type a tag and hit tab, or start typing and select from autocomplete list.",
                related_name="djangocms_blog_tags",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="posttranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="djangocms_blog.Post",
            ),
        ),
    ]
