# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0036_post_linked_content_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked_content_image',
            field=models.URLField(blank=True, help_text='Do not enter value. This is set automatically.', null=True, verbose_name='linked content url'),
        ),
        migrations.AddField(
            model_name='post',
            name='linked_content_thumbnail',
            field=models.URLField(blank=True, help_text='Do not enter value. This is set automatically.', null=True, verbose_name='linked content url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='enable_comments',
            field=models.BooleanField(default=False, verbose_name='enable comments on post'),
        ),
    ]
