# Generated by Django 1.11.24 on 2019-09-14 10:45

import cms.models.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_old_tree_cleanup"),
        ("djangocms_blog", "0037_auto_20190806_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=cms.models.fields.PlaceholderField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                slotname="media",
                to="cms.Placeholder",
            ),
        ),
    ]
