# Generated by Django 2.2 on 2021-10-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0039_auto_20200331_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="include_in_rss",
            field=models.BooleanField(default=True, verbose_name="include in RSS feed"),
        ),
    ]
