# Generated by Django 3.0.14 on 2021-10-26 21:07

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("djangocms_blog", "0039_auto_20200331_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rss_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="djangocms_blog_post_rss_image",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="rss image",
            ),
        ),
    ]
