# Generated by Django 3.0.14 on 2021-12-14 10:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0040_auto_20211128_1503"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "ordering": (
                    django.db.models.expressions.OrderBy(django.db.models.expressions.F("priority"), nulls_last=True),
                ),
                "verbose_name": "blog category",
                "verbose_name_plural": "blog categories",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": "date_published",
                "ordering": (
                    django.db.models.expressions.OrderBy(django.db.models.expressions.F("pinned"), nulls_last=True),
                    "-date_published",
                    "-date_created",
                ),
                "verbose_name": "blog article",
                "verbose_name_plural": "blog articles",
            },
        ),
        migrations.AlterField(
            model_name="blogcategorytranslation",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=752, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pinned",
            field=models.IntegerField(
                blank=True,
                help_text="Pinned posts are shown in ascending order before unpinned ones. Leave blank for regular order by date.",
                null=True,
                verbose_name="pinning priority",
            ),
        ),
    ]
