# Generated by Django 4.2.16 on 2024-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0048_alter_blogcategory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogconfig",
            name="urlconf",
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogcategorytranslation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="paginate_by",
            field=models.SmallIntegerField(
                default=20,
                help_text="When paginating list views, how many articles per page?",
                null=True,
                verbose_name="Paginate size",
            ),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="type",
            field=models.CharField(default="Article", max_length=100, verbose_name="type"),
        ),
        migrations.AlterField(
            model_name="blogconfigtranslation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postcontent",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
