# Generated by Django 4.2.21 on 2025-06-03 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0042_alter_authorentriesplugin_cmsplugin_ptr_and_more"),
        ("djangocms_blog", "0049_remove_blogconfig_urlconf_alter_blogcategory_id_and_more"),
    ]

    operations = []
