# Generated by Django 4.2.21 on 2025-06-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_blog", "0050_merge_20250603_0915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogcategorytranslation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="blogconfig",
            name="type",
            field=models.CharField(max_length=100, verbose_name="type"),
        ),
        migrations.AlterField(
            model_name="blogconfigtranslation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="featuredpostsplugin",
            name="app_config",
            field=models.ForeignKey(
                help_text="When selecting a value, the form is reloaded to get the updated default",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djangocms_blog.blogconfig",
                verbose_name="app. config",
            ),
        ),
        migrations.AlterField(
            model_name="featuredpostsplugin",
            name="template_folder",
            field=models.CharField(
                choices=[("plugins", "Default template")],
                default="plugins",
                help_text="Select plugin layout to load for this instance",
                max_length=200,
                verbose_name="Plugin layout",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
