# Generated by Django 2.1.9 on 2019-06-30 15:55

from django.db import migrations, models
import django.db.models.deletion
import djangocms_blog.media.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vimeo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='media_app_vimeo', serialize=False, to='cms.CMSPlugin')),
                ('url', models.URLField(verbose_name='Video URL')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_blog.media.base.MediaAttachmentPluginMixin, 'cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='YoutTubeVideo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='media_app_youttubevideo', serialize=False, to='cms.CMSPlugin')),
                ('url', models.URLField(verbose_name='video URL')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangocms_blog.media.base.MediaAttachmentPluginMixin, 'cms.cmsplugin'),
        ),
    ]
